// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOfblhVBGQNBDBKSsYEPfAC-6htQGoEiw',
    appId: '1:26099224241:web:468ec47232aeecd5f9dc90',
    messagingSenderId: '26099224241',
    projectId: 'flutterfirebase-3da06',
    authDomain: 'flutterfirebase-3da06.firebaseapp.com',
    storageBucket: 'flutterfirebase-3da06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rpaG-jRDewlFZGTdES178bR9tRb0SkY',
    appId: '1:26099224241:android:34979e7f730ae593f9dc90',
    messagingSenderId: '26099224241',
    projectId: 'flutterfirebase-3da06',
    storageBucket: 'flutterfirebase-3da06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL7N9c4zzkzUifT8kMo74Uo8yjOW9QVwI',
    appId: '1:26099224241:ios:e81353218bf1b8e4f9dc90',
    messagingSenderId: '26099224241',
    projectId: 'flutterfirebase-3da06',
    storageBucket: 'flutterfirebase-3da06.firebasestorage.app',
    iosBundleId: 'com.example.firebaseprontuario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL7N9c4zzkzUifT8kMo74Uo8yjOW9QVwI',
    appId: '1:26099224241:ios:e81353218bf1b8e4f9dc90',
    messagingSenderId: '26099224241',
    projectId: 'flutterfirebase-3da06',
    storageBucket: 'flutterfirebase-3da06.firebasestorage.app',
    iosBundleId: 'com.example.firebaseprontuario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOfblhVBGQNBDBKSsYEPfAC-6htQGoEiw',
    appId: '1:26099224241:web:69e283d3fe48c9dff9dc90',
    messagingSenderId: '26099224241',
    projectId: 'flutterfirebase-3da06',
    authDomain: 'flutterfirebase-3da06.firebaseapp.com',
    storageBucket: 'flutterfirebase-3da06.firebasestorage.app',
  );

}